package com.lovelyhq.lovelydocs.helpers;

import com.lovelyhq.android.lovelydocs.R;
import com.lovelyhq.lovelydocs.models.Docset;

import java.util.ArrayList;
import java.util.List;

public class InitialDocsetsGenerator {
    public static List<Docset> getFullList() {
        List<Docset> docsets = generate();
        docsets.add(new Docset(0, 0, "CouchDB", "CouchDB", 0));
        docsets.add(new Docset(0, 0, "Craft", "Craft", 0));
        docsets.add(new Docset(0, 0, "Docker", "Docker", 0));
        docsets.add(new Docset(0, 0, "Doctrine ORM", "Doctrine_ORM", 0));
        docsets.add(new Docset(0, 0, "Gradle DSL", "Gradle_DSL", 0));
        docsets.add(new Docset(0, 0, "Gradle Groovy API", "Gradle_Groovy_API", 0));
        docsets.add(new Docset(0, 0, "Gradle Java API", "Gradle_Java_API", 0));
        docsets.add(new Docset(0, 0, "Gradle User Guide", "Gradle_User_Guide", 0));
        docsets.add(new Docset(0, 0, "Gulp", "Gulp", 0));
        docsets.add(new Docset(0, 0, "Handlebars", "Handlebars", 0));
        docsets.add(new Docset(0, 0, "Ionic", "Ionic", 0));
        docsets.add(new Docset(0, 0, "Jekyll", "Jekyll", 0));
        docsets.add(new Docset(0, 0, "Jinja", "Jinja", 0));
        docsets.add(new Docset(0, 0, "Julia", "Julia", 0));
        docsets.add(new Docset(0, 0, "Lua 5.3", "Lua_5.3", 0));
        docsets.add(new Docset(0, 0, "MATLAB", "MATLAB", 0));
        docsets.add(new Docset(0, 0, "Matplotlib", "Matplotlib", 0));
        docsets.add(new Docset(0, 0, "Mocha", "Mocha", 0));
        docsets.add(new Docset(0, 0, "Mongoose", "Mongoose", 0));
        docsets.add(new Docset(0, 0, "OS X", "OS_X", 0));
        docsets.add(new Docset(0, 0, "Pandas", "Pandas", 0));
        docsets.add(new Docset(0, 0, "Phalcon", "Phalcon", 0));
        docsets.add(new Docset(0, 0, "Racket", "Racket", 0));
        docsets.add(new Docset(0, 0, "React", "React", 0));
        docsets.add(new Docset(0, 0, "RubyMotion", "RubyMotion", 0));
        docsets.add(new Docset(0, 0, "Ruby on Rails 5", "Ruby_on_Rails_5", 0));
        docsets.add(new Docset(0, 0, "SailsJS", "SailsJS", 0));
        docsets.add(new Docset(0, 0, "Semantic UI", "Semantic_UI", 0));
        docsets.add(new Docset(0, 0, "Susy", "Susy", 0));
        docsets.add(new Docset(0, 0, "TypeScript", "TypeScript", 0));
        docsets.add(new Docset(0, 0, "VueJS", "VueJS", 0));
        docsets.add(new Docset(0, 0, "Xamarin", "Xamarin", 0));
        docsets.add(new Docset(0, 0, "tvOS", "tvOS", 0));
        docsets.add(new Docset(0, 0, "watchOS", "watchOS", 0));
        docsets.add(new Docset(0, 0, "iOS", "iOS", 0));
       // docsets.add(new Docset(0, 0, "AngularTS", "AngularTS", 0));
        return docsets;
    }

    static List<Docset> generateSeptember2016List() {
        List<Docset> docsets = new ArrayList<>();
        docsets.add(new Docset(0, 0, "CouchDB", "CouchDB", 0));
        docsets.add(new Docset(0, 0, "Craft", "Craft", 0));
        docsets.add(new Docset(0, 0, "Docker", "Docker", 0));
        docsets.add(new Docset(0, 0, "Doctrine ORM", "Doctrine_ORM", 0));
        docsets.add(new Docset(0, 0, "Gradle DSL", "Gradle_DSL", 0));
        docsets.add(new Docset(0, 0, "Gradle Groovy API", "Gradle_Groovy_API", 0));
        docsets.add(new Docset(0, 0, "Gradle Java API", "Gradle_Java_API", 0));
        docsets.add(new Docset(0, 0, "Gradle User Guide", "Gradle_User_Guide", 0));
        docsets.add(new Docset(0, 0, "Gulp", "Gulp", 0));
        docsets.add(new Docset(0, 0, "Handlebars", "Handlebars", 0));
        docsets.add(new Docset(0, 0, "Ionic", "Ionic", 0));
        docsets.add(new Docset(0, 0, "Jekyll", "Jekyll", 0));
        docsets.add(new Docset(0, 0, "Jinja", "Jinja", 0));
        docsets.add(new Docset(0, 0, "Julia", "Julia", 0));
        docsets.add(new Docset(0, 0, "Lua 5.3", "Lua_5.3", 0));
        docsets.add(new Docset(0, 0, "MATLAB", "MATLAB", 0));
        docsets.add(new Docset(0, 0, "Matplotlib", "Matplotlib", 0));
        docsets.add(new Docset(0, 0, "Mocha", "Mocha", 0));
        docsets.add(new Docset(0, 0, "Mongoose", "Mongoose", 0));
        docsets.add(new Docset(0, 0, "OS X", "OS_X", 0));
        docsets.add(new Docset(0, 0, "Pandas", "Pandas", 0));
        docsets.add(new Docset(0, 0, "Phalcon", "Phalcon", 0));
        docsets.add(new Docset(0, 0, "Racket", "Racket", 0));
        docsets.add(new Docset(0, 0, "React", "React", 0));
        docsets.add(new Docset(0, 0, "RubyMotion", "RubyMotion", 0));
        docsets.add(new Docset(0, 0, "Ruby on Rails 5", "Ruby_on_Rails_5", 0));
        docsets.add(new Docset(0, 0, "SailsJS", "SailsJS", 0));
        docsets.add(new Docset(0, 0, "Semantic UI", "Semantic_UI", 0));
        docsets.add(new Docset(0, 0, "Susy", "Susy", 0));
        docsets.add(new Docset(0, 0, "TypeScript", "TypeScript", 0));
        docsets.add(new Docset(0, 0, "VueJS", "VueJS", 0));
        docsets.add(new Docset(0, 0, "Xamarin", "Xamarin", 0));
        docsets.add(new Docset(0, 0, "tvOS", "tvOS", 0));
        docsets.add(new Docset(0, 0, "watchOS", "watchOS", 0));
        docsets.add(new Docset(0, 0, "iOS", "iOS", 0));
        //docsets.add(new Docset(0, 0, "AngularTS", "AngularTS", 0));
        return docsets;
    }

    static List<Docset> generate() {
        List<Docset> docsets = new ArrayList<>();
        docsets.add(new Docset(R.drawable.logo_action_script, R.drawable.logo_action_script_pressed, "Action Script", "ActionScript", 0));
        docsets.add(new Docset(R.drawable.logo_akka, R.drawable.logo_akka_pressed, "Akka", "Akka", 0));
        docsets.add(new Docset(R.drawable.logo_android, R.drawable.logo_android_pressed, "Android", "Android", 0));
        docsets.add(new Docset(R.drawable.logo_angular_dart, R.drawable.logo_angular_dart_pressed, "Angular Dart", "Angular.dart", 0));
        docsets.add(new Docset(R.drawable.logo_angular_js, R.drawable.logo_angular_js_pressed, "AngularJS", "AngularJS", 0));
        docsets.add(new Docset(R.drawable.logo_angular_js, R.drawable.logo_angular_js_pressed, "AngularTS", "AngularTS", 0));
        docsets.add(new Docset(R.drawable.logo_ansible, R.drawable.logo_ansible_pressed, "Ansible", "Ansible", 0));
        docsets.add(new Docset(R.drawable.logo_apache, R.drawable.logo_apache_pressed, "Apache", "Apache_HTTP_Server", 0));
        docsets.add(new Docset(R.drawable.logo_appcelerator_titanium, R.drawable.logo_appcelerator_titanium_pressed, "Appcelerator Titanium", "Appcelerator_Titanium", 0));
        docsets.add(new Docset(R.drawable.logo_apple_script, R.drawable.logo_apple_script_pressed, "AppleScript", "AppleScript", 0));
        docsets.add(new Docset(R.drawable.logo_arduino, R.drawable.logo_arduino_pressed, "Arduino", "Arduino", 0));
        docsets.add(new Docset(R.drawable.logo_aws_java_script, R.drawable.logo_aws_java_script_pressed, "AWS JavaScript", "AWS_JavaScript", 0));
        docsets.add(new Docset(R.drawable.logo_backbone, R.drawable.logo_backbone_pressed, "Backbone", "BackboneJS", 0));
        docsets.add(new Docset(R.drawable.logo_bash, R.drawable.logo_bash_pressed, "Bash", "Bash", 0));
        docsets.add(new Docset(R.drawable.logo_boost, R.drawable.logo_boost_pressed, "Boost", "Boost", 0));
        docsets.add(new Docset(R.drawable.logo_bootstrap2, R.drawable.logo_bootstrap2_pressed, "Bootstrap 2", "Bootstrap_2", 0));
        docsets.add(new Docset(R.drawable.logo_bootstrap3, R.drawable.logo_bootstrap3_pressed, "Bootstrap 3", "Bootstrap_3", 0));
        docsets.add(new Docset(R.drawable.logo_bourbon, R.drawable.logo_bourbon_pressed, "Bourbon", "Bourbon", 0));
        docsets.add(new Docset(R.drawable.logo_bourbon_neat, R.drawable.logo_bourbon_neat_pressed, "Bourbon Neat", "Neat", 0));
        docsets.add(new Docset(R.drawable.logo_c, R.drawable.logo_c_pressed, "C", "C", 0));
        docsets.add(new Docset(R.drawable.logo_c_plus_plus, R.drawable.logo_c_plus_plus_pressed, "C++", "C++", 0));
        docsets.add(new Docset(R.drawable.logo_cake_php, R.drawable.logo_cake_php_pressed, "CakePHP", "CakePHP", 0));
        docsets.add(new Docset(R.drawable.logo_cappuccino, R.drawable.logo_cappuccino_pressed, "Cappuccino", "Cappuccino", 0));
        docsets.add(new Docset(R.drawable.logo_chai, R.drawable.logo_chai_pressed, "Chai", "Chai", 0));
        docsets.add(new Docset(R.drawable.logo_chef, R.drawable.logo_chef_pressed, "Chef", "Chef", 0));
        docsets.add(new Docset(R.drawable.logo_clojure, R.drawable.logo_clojure_pressed, "Clojure", "Clojure", 0));
        docsets.add(new Docset(R.drawable.logo_cmake, R.drawable.logo_cmake_pressed, "CMake", "CMake", 0));
        docsets.add(new Docset(R.drawable.logo_cocos_2d, R.drawable.logo_cocos_2d_pressed, "Cocos2D", "Cocos2D", 0));
        docsets.add(new Docset(R.drawable.logo_cocos_2d_x, R.drawable.logo_cocos_2d_x_pressed, "Cocos2D-x", "Cocos2D-X", 0));
        docsets.add(new Docset(R.drawable.logo_cocos_3d, R.drawable.logo_cocos_3d_pressed, "Cocos3D", "Cocos3D", 0));
        docsets.add(new Docset(R.drawable.logo_code_igniter, R.drawable.logo_code_igniter_pressed, "CodeIgniter", "CodeIgniter", 0));
        docsets.add(new Docset(R.drawable.logo_coffee_script, R.drawable.logo_coffee_script_pressed, "CoffeeScript", "CoffeeScript", 0));
        docsets.add(new Docset(R.drawable.logo_cold_fusion, R.drawable.logo_cold_fusion_pressed, "ColdFusion", "ColdFusion", 0));
        docsets.add(new Docset(R.drawable.logo_common_lisp, R.drawable.logo_common_lisp_pressed, "Common Lisp", "Common_Lisp", 0));
        docsets.add(new Docset(R.drawable.logo_compass, R.drawable.logo_compass_pressed, "Compass", "Compass", 0));
        docsets.add(new Docset(R.drawable.logo_cordova, R.drawable.logo_cordova_pressed, "Cordova", "Cordova", 0));
        docsets.add(new Docset(R.drawable.logo_corona, R.drawable.logo_corona_pressed, "Corona", "Corona", 0));
        docsets.add(new Docset(R.drawable.logo_css, R.drawable.logo_css_pressed, "CSS", "CSS", 0));
        docsets.add(new Docset(R.drawable.logo_d3_js, R.drawable.logo_d3_js_pressed, "D3.js", "D3JS", 0));
        docsets.add(new Docset(R.drawable.logo_dart, R.drawable.logo_dart_pressed, "Dart", "Dart", 0));
        docsets.add(new Docset(R.drawable.logo_django, R.drawable.logo_django_pressed, "Django", "Django", 0));
        docsets.add(new Docset(R.drawable.logo_dojo_toolkit, R.drawable.logo_dojo_toolkit_pressed, "Dojo Toolkit", "Dojo", 0));
        docsets.add(new Docset(R.drawable.logo_drupal_7, R.drawable.logo_drupal_7_pressed, "Drupal 7", "Drupal_7", 0));
        docsets.add(new Docset(R.drawable.logo_drupal_8, R.drawable.logo_drupal_8_pressed, "Drupal 8", "Drupal_8", 0));
        docsets.add(new Docset(R.drawable.logo_elastic_search, R.drawable.logo_elastic_search_pressed, "ElasticSearch", "ElasticSearch", 0));
        docsets.add(new Docset(R.drawable.logo_elixir, R.drawable.logo_elixir_pressed, "Elixir", "Elixir", 0));
        docsets.add(new Docset(R.drawable.logo_emacs_lisp, R.drawable.logo_emacs_lisp_pressed, "Emacs Lisp", "Emacs_Lisp", 0));
        docsets.add(new Docset(R.drawable.logo_ember_js, R.drawable.logo_ember_js_pressed, "Ember.js", "EmberJS", 0));
        docsets.add(new Docset(R.drawable.logo_emmet_io, R.drawable.logo_emmet_io_pressed, "Emmet.io", "Emmet", 0));
        docsets.add(new Docset(R.drawable.logo_erlang, R.drawable.logo_erlang_pressed, "Erlang", "Erlang", 0));
        docsets.add(new Docset(R.drawable.logo_express_js, R.drawable.logo_express_js_pressed, "Express.js", "Express", 0));
        docsets.add(new Docset(R.drawable.logo_expression_engine, R.drawable.logo_expression_engine_pressed, "ExpressionEngine", "ExpressionEngine", 0));
        docsets.add(new Docset(R.drawable.logo_ext_js, R.drawable.logo_ext_js_pressed, "ExtJS", "ExtJS", 0));
        docsets.add(new Docset(R.drawable.logo_flask, R.drawable.logo_flask_pressed, "Flask", "Flask", 0));
        docsets.add(new Docset(R.drawable.logo_font_awesome, R.drawable.logo_font_awesome_pressed, "FontAwesome", "Font_Awesome", 0));
        docsets.add(new Docset(R.drawable.logo_foundation, R.drawable.logo_foundation_pressed, "Foundation", "Foundation", 0));
        docsets.add(new Docset(R.drawable.logo_glib, R.drawable.logo_glib_pressed, "GLib", "GLib", 0));
        docsets.add(new Docset(R.drawable.logo_go, R.drawable.logo_go_pressed, "Go", "Go", 0));
        docsets.add(new Docset(R.drawable.logo_grails, R.drawable.logo_grails_pressed, "Grails", "Grails", 0));
        docsets.add(new Docset(R.drawable.logo_groovy, R.drawable.logo_groovy_pressed, "Groovy", "Groovy", 0));
        docsets.add(new Docset(R.drawable.logo_groovy_jdk, R.drawable.logo_groovy_jdk_pressed, "Groovy JDK", "Groovy_JDK", 0));
        docsets.add(new Docset(R.drawable.logo_grunt, R.drawable.logo_grunt_pressed, "Grunt", "Grunt", 0));
        docsets.add(new Docset(R.drawable.logo_haml, R.drawable.logo_haml_pressed, "Haml", "Haml", 0));
        docsets.add(new Docset(R.drawable.logo_haskell, R.drawable.logo_haskell_pressed, "Haskell", "Haskell", 0));
        docsets.add(new Docset(R.drawable.logo_html, R.drawable.logo_html_pressed, "HTML", "HTML", 0));
        docsets.add(new Docset(R.drawable.logo_jade, R.drawable.logo_jade_pressed, "Jade", "Jade", 0));
        docsets.add(new Docset(R.drawable.logo_jasmine, R.drawable.logo_jasmine_pressed, "Jasmine", "Jasmine", 0));
        docsets.add(new Docset(R.drawable.logo_java_se6, R.drawable.logo_java_se6_pressed, "Java SE6", "Java_SE6", 0));
        docsets.add(new Docset(R.drawable.logo_java_se7, R.drawable.logo_java_se7_pressed, "Java SE7", "Java_SE7", 0));
        docsets.add(new Docset(R.drawable.logo_java_se8, R.drawable.logo_java_se8_pressed, "Java SE8", "Java_SE8", 0));
        docsets.add(new Docset(R.drawable.logo_java_ee6, R.drawable.logo_java_ee6_pressed, "Java EE6", "Java_EE6", 0));
        docsets.add(new Docset(R.drawable.logo_java_ee7, R.drawable.logo_java_ee7_pressed, "Java EE7", "Java_EE7", 0));
        docsets.add(new Docset(R.drawable.logo_java_fx, R.drawable.logo_java_fx_pressed, "Java FX", "JavaFX", 0));
        docsets.add(new Docset(R.drawable.logo_java_script, R.drawable.logo_java_script_pressed, "JavaScript", "JavaScript", 0));
        docsets.add(new Docset(R.drawable.logo_joomla, R.drawable.logo_joomla_pressed, "Joomla", "Joomla", 0));
        docsets.add(new Docset(R.drawable.logo_jquery, R.drawable.logo_jquery_pressed, "jQuery", "jQuery", 0));
        docsets.add(new Docset(R.drawable.logo_jquery_mobile, R.drawable.logo_jquery_mobile_pressed, "jQuery Mobile", "jQuery_Mobile", 0));
        docsets.add(new Docset(R.drawable.logo_jquery_ui, R.drawable.logo_jquery_ui_pressed, "jQuery UI", "jQuery_UI", 0));
        docsets.add(new Docset(R.drawable.logo_knockout_js, R.drawable.logo_knockout_js_pressed, "Knockout.js", "KnockoutJS", 0));
        docsets.add(new Docset(R.drawable.logo_kobold2d, R.drawable.logo_kobold2d_pressed, "Kobold2D", "Kobold2D", 0));
        docsets.add(new Docset(R.drawable.logo_laravel, R.drawable.logo_laravel_pressed, "Laravel", "Laravel", 0));
        docsets.add(new Docset(R.drawable.logo_latex, R.drawable.logo_latex_pressed, "LaTeX", "LaTeX", 0));
        docsets.add(new Docset(R.drawable.logo_less, R.drawable.logo_less_pressed, "Less", "Less", 0));
        docsets.add(new Docset(R.drawable.logo_lo_dash, R.drawable.logo_lo_dash_pressed, "Lo-dash", "Lo-Dash", 0));
        docsets.add(new Docset(R.drawable.logo_lua_5_1, R.drawable.logo_lua_5_1_pressed, "Lua 5.1", "Lua_5.1", 0));
        docsets.add(new Docset(R.drawable.logo_lua_5_2, R.drawable.logo_lua_5_2_pressed, "Lua 5.2", "Lua_5.2", 0));
        docsets.add(new Docset(R.drawable.logo_marionette_js, R.drawable.logo_marionette_js_pressed, "Marionette.js", "MarionetteJS", 0));
        docsets.add(new Docset(R.drawable.logo_markdown, R.drawable.logo_markdown_pressed, "Markdown", "Markdown", 0));
        docsets.add(new Docset(R.drawable.logo_meteor, R.drawable.logo_meteor_pressed, "Meteor", "Meteor", 0));
        docsets.add(new Docset(R.drawable.logo_moment_js, R.drawable.logo_moment_js_pressed, "Moment.js", "MomentJS", 0));
        docsets.add(new Docset(R.drawable.logo_mongo_db, R.drawable.logo_mongo_db_pressed, "MongoDB", "MongoDB", 0));
        docsets.add(new Docset(R.drawable.logo_mono, R.drawable.logo_mono_pressed, "Mono", "Mono", 0));
        docsets.add(new Docset(R.drawable.logo_moo_tools, R.drawable.logo_moo_tools_pressed, "MooTools", "MooTools", 0));
        docsets.add(new Docset(R.drawable.logo_mysql, R.drawable.logo_mysql_pressed, "MySQL", "MySQL", 0));
        docsets.add(new Docset(R.drawable.logo_net_framework, R.drawable.logo_net_framework_pressed, "NET Framework", "NET_Framework", 0));
        docsets.add(new Docset(R.drawable.logo_nginx, R.drawable.logo_nginx_pressed, "Nginx", "Nginx", 0));
        docsets.add(new Docset(R.drawable.logo_node_js, R.drawable.logo_node_js_pressed, "Node.js", "NodeJS", 0));
        docsets.add(new Docset(R.drawable.logo_py_num, R.drawable.logo_py_num_pressed, "NumPy", "NumPy", 0));
        docsets.add(new Docset(R.drawable.logo_ocaml, R.drawable.logo_ocaml_pressed, "OCaml", "OCaml", 0));
        docsets.add(new Docset(R.drawable.logo_opencv, R.drawable.logo_opencv_pressed, "OpenCV C", "OpenCV_C", 0));
        docsets.add(new Docset(R.drawable.logo_opencv, R.drawable.logo_opencv_pressed, "OpenCV C++", "OpenCV_C++", 0));
        docsets.add(new Docset(R.drawable.logo_opencv, R.drawable.logo_opencv_pressed, "OpenCV Java", "OpenCV_Java", 0));
        docsets.add(new Docset(R.drawable.logo_opencv, R.drawable.logo_opencv_pressed, "OpenCV Python", "OpenCV_Python", 0));
        docsets.add(new Docset(R.drawable.logo_open_gl, R.drawable.logo_open_gl_pressed, "OpenGL 2", "OpenGL_2", 0));
        docsets.add(new Docset(R.drawable.logo_open_gl, R.drawable.logo_open_gl_pressed, "OpenGL 3", "OpenGL_3", 0));
        docsets.add(new Docset(R.drawable.logo_open_gl, R.drawable.logo_open_gl_pressed, "OpenGL 4", "OpenGL_4", 0));
        docsets.add(new Docset(R.drawable.logo_perl, R.drawable.logo_perl_pressed, "Perl", "Perl", 0));
        docsets.add(new Docset(R.drawable.logo_phone_gap, R.drawable.logo_phone_gap_pressed, "PhoneGap", "PhoneGap", 0));
        docsets.add(new Docset(R.drawable.logo_php, R.drawable.logo_php_pressed, "PHP", "PHP", 0));
        docsets.add(new Docset(R.drawable.logo_php_unit, R.drawable.logo_php_unit_pressed, "PHPUnit", "PHPUnit", 0));
        docsets.add(new Docset(R.drawable.logo_play, R.drawable.logo_play_pressed, "Play Java", "Play_Java", 0));
        docsets.add(new Docset(R.drawable.logo_play, R.drawable.logo_play_pressed, "Play Scala", "Play_Scala", 0));
        docsets.add(new Docset(R.drawable.logo_polymer_dart, R.drawable.logo_polymer_dart_pressed, "Polymer.dart", "Polymer.dart", 0));
        docsets.add(new Docset(R.drawable.logo_postgre_sql, R.drawable.logo_postgre_sql_pressed, "PostgreSQL", "PostgreSQL", 0));
        docsets.add(new Docset(R.drawable.logo_processing_org, R.drawable.logo_processing_org_pressed, "Processing.org", "Processing", 0));
        docsets.add(new Docset(R.drawable.logo_prototype, R.drawable.logo_prototype_pressed, "Prototype", "PrototypeJS", 0));
        docsets.add(new Docset(R.drawable.logo_puppet, R.drawable.logo_puppet_pressed, "Puppet", "Puppet", 0));
        docsets.add(new Docset(R.drawable.logo_python_2, R.drawable.logo_python_2_pressed, "Python 2", "Python_2", 0));
        docsets.add(new Docset(R.drawable.logo_python_3, R.drawable.logo_python_3_pressed, "Python 3", "Python_3", 0));
        docsets.add(new Docset(R.drawable.logo_qt, R.drawable.logo_qt_pressed, "Qt 4", "Qt_4", 0));
        docsets.add(new Docset(R.drawable.logo_qt, R.drawable.logo_qt_pressed, "Qt 5", "Qt_5", 0));
        docsets.add(new Docset(R.drawable.logo_r, R.drawable.logo_r_pressed, "R", "R", 0));
        docsets.add(new Docset(R.drawable.logo_redis, R.drawable.logo_redis_pressed, "Redis", "Redis", 0));
        docsets.add(new Docset(R.drawable.logo_require_js, R.drawable.logo_require_js_pressed, "RequireJS", "RequireJS", 0));
        docsets.add(new Docset(R.drawable.logo_ruby, R.drawable.logo_ruby_pressed, "Ruby", "Ruby", 0));
        docsets.add(new Docset(R.drawable.logo_ruby, R.drawable.logo_ruby_pressed, "Ruby 2", "Ruby_2", 0));
        docsets.add(new Docset(R.drawable.logo_ruby_on_rails, R.drawable.logo_ruby_on_rails_pressed, "Ruby on Rails 3", "Ruby_on_Rails_3", 0));
        docsets.add(new Docset(R.drawable.logo_ruby_on_rails, R.drawable.logo_ruby_on_rails_pressed, "Ruby on Rails 4", "Ruby_on_Rails_4", 0));
        docsets.add(new Docset(R.drawable.logo_rust, R.drawable.logo_rust_pressed, "Rust", "Rust", 0));
        docsets.add(new Docset(R.drawable.logo_salt_stack, R.drawable.logo_salt_stack_pressed, "SaltStack", "SaltStack", 0));
        docsets.add(new Docset(R.drawable.logo_sass, R.drawable.logo_sass_pressed, "Sass", "Sass", 0));
        docsets.add(new Docset(R.drawable.logo_scala, R.drawable.logo_scala_pressed, "Scala", "Scala", 0));
        docsets.add(new Docset(R.drawable.logo_sci_py, R.drawable.logo_sci_py_pressed, "SciPy", "SciPy", 0));
        docsets.add(new Docset(R.drawable.logo_sencha_touch, R.drawable.logo_sencha_touch_pressed, "Sencha Touch", "Sencha_Touch", 0));
        docsets.add(new Docset(R.drawable.logo_sinon_js, R.drawable.logo_sinon_js_pressed, "Sinon", "Sinon", 0));
        docsets.add(new Docset(R.drawable.logo_smarty, R.drawable.logo_smarty_pressed, "Smarty", "Smarty", 0));
        docsets.add(new Docset(R.drawable.logo_sparrow, R.drawable.logo_sparrow_pressed, "Sparrow", "Sparrow", 0));
        docsets.add(new Docset(R.drawable.logo_spring_framework, R.drawable.logo_spring_framework_pressed, "Spring Framework", "Spring_Framework", 0));
        docsets.add(new Docset(R.drawable.logo_sql_alchemy, R.drawable.logo_sql_alchemy_pressed, "SQLAlchemy", "SQLAlchemy", 0));
        docsets.add(new Docset(R.drawable.logo_sql_lite, R.drawable.logo_sql_lite_pressed, "SQLite", "SQLite", 0));
        docsets.add(new Docset(R.drawable.logo_statamic, R.drawable.logo_statamic_pressed, "Statamic", "Statamic", 0));
        docsets.add(new Docset(R.drawable.logo_stylus, R.drawable.logo_stylus_pressed, "Stylus", "Stylus", 0));
        docsets.add(new Docset(R.drawable.logo_svg, R.drawable.logo_svg_pressed, "SVG", "SVG", 0));
        docsets.add(new Docset(R.drawable.logo_swift, R.drawable.logo_swift_pressed, "Swift", "Swift", 0));
        docsets.add(new Docset(R.drawable.logo_symfony, R.drawable.logo_symfony_pressed, "Symfony", "Symfony", 0));
        docsets.add(new Docset(R.drawable.logo_tcl, R.drawable.logo_tcl_pressed, "Tcl", "Tcl", 0));
        docsets.add(new Docset(R.drawable.logo_tornado, R.drawable.logo_tornado_pressed, "Tornado", "Tornado", 0));
        docsets.add(new Docset(R.drawable.logo_twig, R.drawable.logo_twig_pressed, "Twig", "Twig", 0));
        docsets.add(new Docset(R.drawable.logo_twisted, R.drawable.logo_twisted_pressed, "Twisted", "Twisted", 0));
        docsets.add(new Docset(R.drawable.logo_typo_3, R.drawable.logo_typo_3_pressed, "TYPO3", "TYPO3", 0));
        docsets.add(new Docset(R.drawable.logo_underscore_js, R.drawable.logo_underscore_js_pressed, "Underscore.js", "UnderscoreJS", 0));
        docsets.add(new Docset(R.drawable.logo_unity_3d, R.drawable.logo_unity_3d_pressed, "Unity3D", "Unity_3D", 0));
        docsets.add(new Docset(R.drawable.logo_vagrant, R.drawable.logo_vagrant_pressed, "Vagrant", "Vagrant", 0));
        docsets.add(new Docset(R.drawable.logo_vim, R.drawable.logo_vim_pressed, "Vim", "Vim", 0));
        docsets.add(new Docset(R.drawable.logo_vmware_vsphere, R.drawable.logo_vmware_vsphere_pressed, "VMware vSphere", "VMware_vSphere", 0));
        docsets.add(new Docset(R.drawable.logo_wordpress, R.drawable.logo_wordpress_pressed, "WordPress", "WordPress", 0));
        docsets.add(new Docset(R.drawable.logo_xojo, R.drawable.logo_xojo_pressed, "Xojo", "Xojo", 0));
        docsets.add(new Docset(R.drawable.logo_xslt, R.drawable.logo_xslt_pressed, "XSLT", "XSLT", 0));
        docsets.add(new Docset(R.drawable.logo_xul, R.drawable.logo_xul_pressed, "XUL", "XUL", 0));
        docsets.add(new Docset(R.drawable.logo_yii, R.drawable.logo_yii_pressed, "Yii", "Yii", 0));
        docsets.add(new Docset(R.drawable.logo_yui, R.drawable.logo_yui_pressed, "YUI", "YUI", 0));
        docsets.add(new Docset(R.drawable.logo_zend, R.drawable.logo_zend_pressed, "Zend Framework 1", "Zend_Framework_1", 0));
        docsets.add(new Docset(R.drawable.logo_zend, R.drawable.logo_zend_pressed, "Zend Framework 2", "Zend_Framework_2", 0));
        docsets.add(new Docset(R.drawable.logo_zepto_js, R.drawable.logo_zepto_js_pressed, "Zepto.js", "ZeptoJS", 0));
        return docsets;
    }
}
